import React, { useEffect, useMemo, useRef, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { gsap } from 'gsap'
import { BarChart3, Car, ChevronRight, CreditCard, Edit3, IndianRupee, LayoutDashboard, Menu, Plus, Search, Trash2, X } from 'lucide-react'
import { getData, saveCar, removeCar, addPayment } from './lib/api'
import { configured } from './lib/supabase'
import { money, date, paymentStatus, todayInput } from './lib/format'
import './styles.css'

const washTypes = ['Daily Clean', 'Alternate Days', 'Weekly Twice', 'Weekly Once', 'One-Time Wash']
const blankCar = { customer_name: '', phone: '', vehicle_number: '', car_model: '', wash_type: 'Daily Clean', amount: '', service_date: todayInput(), notes: '' }
const statusClass = { Paid: 'paid', 'Partially Paid': 'partial', Pending: 'pending' }
const paymentMethods = ['Cash', 'UPI', 'Card', 'Bank Transfer', 'Other']

function Toast({ toast }) { return toast && <div className={'toast ' + toast.kind}>{toast.text}</div> }
function Modal({ children, onClose, title }) { const ref = useRef(null); useEffect(() => { if (!matchMedia('(prefers-reduced-motion: reduce)').matches) gsap.fromTo(ref.current, { y: 12, opacity: 0 }, { y: 0, opacity: 1, duration: .22 }); }, []); return <div className="overlay" onMouseDown={onClose}><section className="modal" ref={ref} onMouseDown={e => e.stopPropagation()} role="dialog" aria-modal="true"><div className="modal-head"><h2>{title}</h2><button className="icon-button" onClick={onClose} aria-label="Close"><X size={20}/></button></div>{children}</section></div> }
function Status({ status }) { return <span className={'badge ' + statusClass[status]}>{status}</span> }
function Field({ label, children, required }) { return <label className="field"><span>{label}{required && <b> *</b>}</span>{children}</label> }
function Skeleton() { return <div className="skeletons">{[1,2,3,4].map(i => <div className="skeleton" key={i}/>)}</div> }

function CarForm({ car, onClose, refresh, notify }) {
 const [values, setValues] = useState(car ? { ...car, amount: String(car.amount), service_date: car.service_date || '' } : blankCar), [saving, setSaving] = useState(false), [error, setError] = useState('')
 const change = e => setValues(v => ({ ...v, [e.target.name]: e.target.value }))
 async function submit(e) { e.preventDefault(); if (!values.customer_name.trim() || !values.vehicle_number.trim() || !values.wash_type || values.amount === '' || Number(values.amount) < 0) return setError('Please complete all required fields with a valid amount.'); setSaving(true); try { await saveCar(values, car?.id); await refresh(); notify(car ? 'Car record updated.' : 'Car added successfully.'); onClose() } catch (err) { setError(err.message) } finally { setSaving(false) } }
 return <form onSubmit={submit} className="form"><div className="form-grid"><Field label="Customer name" required><input name="customer_name" value={values.customer_name} onChange={change} autoFocus/></Field><Field label="Phone number"><input name="phone" value={values.phone || ''} onChange={change} inputMode="tel"/></Field><Field label="Vehicle number" required><input name="vehicle_number" value={values.vehicle_number} onChange={change} className="uppercase"/></Field><Field label="Car model"><input name="car_model" value={values.car_model || ''} onChange={change}/></Field><Field label="Wash type" required><select name="wash_type" value={values.wash_type} onChange={change}>{washTypes.map(x => <option key={x}>{x}</option>)}</select></Field><Field label="Service amount" required><input name="amount" type="number" min="0" step="0.01" value={values.amount} onChange={change} inputMode="decimal"/></Field><Field label="Service date"><input name="service_date" type="date" value={values.service_date || ''} onChange={change}/></Field></div><Field label="Notes"><textarea name="notes" value={values.notes || ''} onChange={change} rows="3"/></Field>{error && <p className="form-error">{error}</p>}<div className="form-actions"><button type="button" className="button secondary" onClick={onClose}>Cancel</button><button className="button" disabled={saving}>{saving ? 'Saving…' : car ? 'Save changes' : 'Add car'}</button></div></form>
}
function PaymentForm({ car, paid, onClose, refresh, notify }) {
 const remaining = Math.max(Number(car.amount) - paid, 0), [values, setValues] = useState({ amount: '', payment_method: 'Cash', payment_date: todayInput(), note: '' }), [error, setError] = useState(''), [saving, setSaving] = useState(false)
 const change = e => setValues(v => ({...v, [e.target.name]: e.target.value}))
 async function submit(e) { e.preventDefault(); const amount = Number(values.amount); if (!(amount > 0) || amount > remaining) return setError(`Enter an amount from ₹1 to ${money(remaining)}.`); setSaving(true); try { await addPayment({ ...values, car_id: car.id, payment_date: new Date(values.payment_date).toISOString() }); await refresh(); notify('Payment recorded successfully.'); onClose() } catch (err) { setError(err.message) } finally { setSaving(false) } }
 return <form className="form" onSubmit={submit}><div className="summary-strip"><span>Outstanding</span><strong>{money(remaining)}</strong></div><Field label="Amount" required><input name="amount" type="number" min="1" max={remaining} step="0.01" value={values.amount} onChange={change} autoFocus inputMode="decimal"/></Field><div className="form-grid"><Field label="Payment method"><select name="payment_method" value={values.payment_method} onChange={change}>{paymentMethods.map(x => <option key={x}>{x}</option>)}</select></Field><Field label="Payment date"><input name="payment_date" type="date" value={values.payment_date} onChange={change}/></Field></div><Field label="Note"><textarea name="note" value={values.note} onChange={change} rows="2"/></Field>{error && <p className="form-error">{error}</p>}<div className="form-actions"><button type="button" className="button secondary" onClick={onClose}>Cancel</button><button className="button" disabled={saving}>{saving ? 'Recording…' : 'Record payment'}</button></div></form>
}

function App() {
 const [page, setPage] = useState('Dashboard'), [cars, setCars] = useState([]), [payments, setPayments] = useState([]), [loading, setLoading] = useState(configured), [error, setError] = useState(''), [menu, setMenu] = useState(false), [modal, setModal] = useState(null), [toast, setToast] = useState(null), [search, setSearch] = useState(''), [statusFilter, setStatusFilter] = useState('All'), [washFilter, setWashFilter] = useState('All')
 const content = useRef(null)
 const notify = (text, kind='success') => { setToast({text,kind}); setTimeout(() => setToast(null), 3500) }
 const refresh = async () => { setLoading(true); setError(''); try { const d = await getData(); setCars(d.cars); setPayments(d.payments) } catch (e) { setError(e.message) } finally { setLoading(false) } }
 useEffect(() => { if (configured) refresh(); else setLoading(false) }, [])
 useEffect(() => { if (content.current && !matchMedia('(prefers-reduced-motion: reduce)').matches) gsap.fromTo(content.current, { opacity: 0, y: 5 }, { opacity: 1, y: 0, duration: .25 }) }, [page])
 const derived = useMemo(() => cars.map(car => { const carPayments = payments.filter(p => p.car_id === car.id); const paid = carPayments.reduce((sum,p) => sum + Number(p.amount), 0); return {...car, paid, outstanding: Math.max(Number(car.amount) - paid, 0), status: paymentStatus(car.amount, paid), paymentList: carPayments} }), [cars,payments])
 const kpis = useMemo(() => { const billed = cars.reduce((s,c) => s + Number(c.amount),0), paid = payments.reduce((s,p) => s+Number(p.amount),0); const now = new Date(), day = now.toDateString(); return { billed, paid, outstanding: Math.max(billed-paid,0), today: payments.filter(p => new Date(p.payment_date).toDateString() === day).reduce((s,p)=>s+Number(p.amount),0), month: payments.filter(p=>{const d=new Date(p.payment_date);return d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear()}).reduce((s,p)=>s+Number(p.amount),0), pending: derived.filter(c=>c.outstanding>0).length } }, [cars,payments,derived])
 const filtered = derived.filter(c => { const q = search.toLowerCase(); return (!q || [c.customer_name,c.vehicle_number,c.phone,c.car_model].some(x => String(x||'').toLowerCase().includes(q))) && (statusFilter==='All'||c.status===statusFilter) && (washFilter==='All'||c.wash_type===washFilter) })
 function go(to){ setPage(to); setMenu(false) }
 function deleteCar(car) { setModal({type:'delete', car}) }
 function Dashboard() { const recent = payments.slice(0,5); return <><div className="page-title"><div><p className="eyebrow">BUSINESS OVERVIEW</p><h1>Good to see you.</h1><p className="muted">Here’s how Kishore Car Care is doing today.</p></div><button className="button" onClick={()=>setModal({type:'car'})}><Plus size={18}/> Add car</button></div>{loading ? <Skeleton/> : <>{error && <div className="notice error">{error}</div>}<div className="kpis">{[[Car,'Total Cars',cars.length,'records'],[IndianRupee,'Total Billed',money(kpis.billed),'service value'],[CreditCard,'Total Paid',money(kpis.paid),'collections'],[BarChart3,'Outstanding',money(kpis.outstanding),'to collect']].map(([Icon,label,value,sub])=><article className="kpi" key={label}><div className="kpi-icon"><Icon size={20}/></div><p>{label}</p><h2>{value}</h2><small>{sub}</small></article>)}</div><div className="dash-grid"><section className="panel collections"><div className="panel-head"><div><h2>Collections</h2><p>Current calendar month</p></div><strong>{money(kpis.month)}</strong></div><div className="simple-chart">{[...Array(7)].map((_,i)=>{const d=new Date();d.setDate(d.getDate()-6+i);const value=payments.filter(p=>new Date(p.payment_date).toDateString()===d.toDateString()).reduce((s,p)=>s+Number(p.amount),0);const max=Math.max(...payments.map(p=>Number(p.amount)),1);return <div className="bar-wrap" key={i}><div className="bar" style={{height:`${Math.max(5, value/max*100)}%`}} title={money(value)}/><small>{d.toLocaleDateString('en-IN',{weekday:'short'})}</small></div>})}</div></section><section className="panel"><div className="panel-head"><div><h2>Quick snapshot</h2><p>Payment health</p></div></div><div className="stats"><div><span>Today’s collections</span><b>{money(kpis.today)}</b></div><div><span>Pending payments</span><b>{kpis.pending}</b></div></div></section></div><section className="panel recent"><div className="panel-head"><div><h2>Recent payments</h2><p>Latest recorded collections</p></div><button className="text-button" onClick={()=>go('Cars')}>View cars <ChevronRight size={16}/></button></div>{recent.length ? recent.map(p=>{const c=cars.find(x=>x.id===p.car_id); return <div className="payment-row" key={p.id}><div className="avatar">{(c?.customer_name||'?')[0]}</div><div><b>{c?.customer_name||'Deleted car'}</b><span>{c?.vehicle_number||'—'} · {p.payment_method}</span></div><strong>{money(p.amount)}</strong><small>{date(p.payment_date)}</small></div>}) : <div className="empty compact">No payments recorded yet.</div>}</section></>}</> }
 function Cars() { return <><div className="page-title"><div><p className="eyebrow">CAR & SERVICE TRACKER</p><h1>Cars</h1><p className="muted">Manage customer services, balances and payments.</p></div><button className="button" onClick={()=>setModal({type:'car'})}><Plus size={18}/> Add car</button></div><div className="filters"><div className="search"><Search size={18}/><input aria-label="Search cars" placeholder="Search customer, vehicle, phone or model" value={search} onChange={e=>setSearch(e.target.value)}/></div><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option>All</option><option>Paid</option><option>Partially Paid</option><option>Pending</option></select><select value={washFilter} onChange={e=>setWashFilter(e.target.value)}><option>All</option>{washTypes.map(x=><option key={x}>{x}</option>)}</select></div>{loading?<Skeleton/>:error?<div className="notice error">{error}</div>:filtered.length?<div className="car-list">{filtered.map(car=><article className="car-card" key={car.id}><div className="car-main"><div className="avatar purple">{car.customer_name[0]}</div><div><h2>{car.customer_name}</h2><p>{car.vehicle_number.toUpperCase()} {car.car_model && `· ${car.car_model}`}</p></div><Status status={car.status}/></div><div className="car-tags"><span>{car.wash_type}</span><span>{date(car.service_date)}</span></div><div className="amounts"><div><span>Total</span><b>{money(car.amount)}</b></div><div><span>Paid</span><b className="green">{money(car.paid)}</b></div><div><span>Due</span><b className="orange">{money(car.outstanding)}</b></div></div><div className="car-actions"><button className="button small" disabled={car.outstanding<=0} onClick={()=>setModal({type:'payment',car})}><CreditCard size={16}/> Record payment</button><button className="icon-button" aria-label="Edit" onClick={()=>setModal({type:'edit',car})}><Edit3 size={17}/></button><button className="icon-button danger" aria-label="Delete" onClick={()=>deleteCar(car)}><Trash2 size={17}/></button></div>{car.paymentList.length>0&&<details><summary>Payment history ({car.paymentList.length})</summary>{car.paymentList.map(p=><div className="history" key={p.id}><span>{date(p.payment_date)} · {p.payment_method}</span><b>{money(p.amount)}</b></div>)}</details>}</article>)}</div>:<div className="empty"><Car size={32}/><h2>No cars added yet</h2><p>Start tracking your customers and services.</p><button className="button" onClick={()=>setModal({type:'car'})}><Plus size={18}/> Add your first car</button></div>}</> }
 return <div className="app-shell"><aside className={menu?'sidebar open':'sidebar'}><div className="brand"><div className="brand-mark">K</div><div><b>Kishore</b><span>CAR CARE</span></div><button className="mobile-close icon-button" onClick={()=>setMenu(false)}><X/></button></div><nav>{[[LayoutDashboard,'Dashboard'],[Car,'Cars']].map(([Icon,name])=><button key={name} className={page===name?'active':''} onClick={()=>go(name)}><Icon size={19}/>{name}</button>)}</nav><div className="sidebar-foot">Built for better service</div></aside>{menu&&<div className="backdrop" onClick={()=>setMenu(false)}/>}<main><header className="topbar"><button className="hamburger icon-button" onClick={()=>setMenu(true)} aria-label="Open navigation"><Menu/></button><span className="mobile-brand">Kishore Car Care</span><div className="status-dot"><i/> Live dashboard</div></header><div className="content" ref={content}>{page==='Dashboard'?<Dashboard/>:<Cars/>}</div></main>{modal?.type==='car'&&<Modal title="Add car" onClose={()=>setModal(null)}><CarForm onClose={()=>setModal(null)} refresh={refresh} notify={notify}/></Modal>}{modal?.type==='edit'&&<Modal title="Edit car" onClose={()=>setModal(null)}><CarForm car={modal.car} onClose={()=>setModal(null)} refresh={refresh} notify={notify}/></Modal>}{modal?.type==='payment'&&<Modal title="Record payment" onClose={()=>setModal(null)}><PaymentForm car={modal.car} paid={modal.car.paid} onClose={()=>setModal(null)} refresh={refresh} notify={notify}/></Modal>}{modal?.type==='delete'&&<Modal title="Delete car record?" onClose={()=>setModal(null)}><p className="confirm-copy">Are you sure you want to delete this car record? This action cannot be undone.</p><div className="form-actions"><button className="button secondary" onClick={()=>setModal(null)}>Cancel</button><button className="button destructive" onClick={async()=>{try{await removeCar(modal.car.id);await refresh();notify('Car record deleted.');setModal(null)}catch(e){notify(e.message,'error')}}>Delete record</button></div></Modal>}<Toast toast={toast}/></div>
}
createRoot(document.getElementById('root')).render(<App />)

